/**
 * @file messages.c
 * @copyright 2026 Ivan Kniazkov
 * @brief Implements message handling with language selection.
 */

#include "messages.h"

#include <ctype.h>
#include <stdlib.h>
#include <string.h>

/** @brief The message structure for English language. */
static messages_t english = {
    .help = L"Usage: goat [options] <input_file> [script arguments...]\n"
            L"\n"
            L"Options:\n"
            L"  --compile                    Save <name>.gbin without execution\n"
            L"  --run                        Execute a .gbin without compiling (native: auto)\n"
            L"  --optimize <none|all>         Optimization level (default: all)\n"
            L"  --native <off|auto|required>  Native execution (default: off)\n"
            L"  --print-native               Print native execution counters\n"
            L"  --save-native <file>         Save native execution counters\n"
            L"  --print-analysis              Print analysis observations\n"
            L"  --save-analysis <file>      Save analysis observations as UTF-8\n"
            L"  --print-c                    Print C module without executing the program\n"
            L"  --save-c                     Save C module beside input as <name>.c\n"
            L"  --save-library               Build <name>.so/.dll without execution (CC)\n"
            L"  --print-bytecode              Print generated bytecode\n"
            L"  --print-source-code           Print regenerated Goat source code\n"
            L"  --save-graph <file.png|svg>  Generate AST graph image\n"
            L"  -l, --lang, --language <lang> Select message language\n"
            L"  -w, --enable-warnings         Enable compiler warnings\n"
            L"  -h, --help, /?                Show this help message\n",
    .memory_leak = L"Memory leak of %zu bytes detected",
    .no_input_file = L"Input file not specified",
    .unknown_option = L"Unknown option: '%a'",
    .missing_specification = L"Missing value for parameter '%a'",
    .bad_optimization_level = L"Unknown optimization level: '%a' (expected none or all)",
    .bad_native_mode = L"Unknown native mode: '%a' (expected off, auto or required)",
    .bad_native_options = L"Native execution requires --optimize all; C/library export cannot be "
                          L"combined with native execution or reports",
    .native_report_conflict = L"Native report must not overwrite its input",
    .cannot_write_native_report = L"Could not write native report to '%a'",
    .native_prepare_failed = L"Native preparation failed (%a): %a",
    .bad_c_options =
        L"C export requires --optimize all and cannot be combined with other --print options",
    .cannot_write_c_file = L"Could not write C source to '%a' (the input must not be overwritten)",
    .c_omitted = L"C generation omitted %s: %s",
    .native_compile_failed = L"Native compilation failed (%s): compiler '%a', output '%a', "
                             L"exit %ld, signal %d, system error %a, cleanup error %a, Win32 "
                             L"error %u, Win32 cleanup %u",
    .native_diagnostics_truncated = L"Compiler diagnostics truncated at 65536 bytes",
    .native_input_conflict = L"Library output must not overwrite its input",
    .bad_graph_file = L"The graph image file must be of type PNG or SVG",
    .no_graphviz =
        L"The GraphViz tool required for graph visualization is not installed on the system",
    .graphviz_failed = L"The GraphViz tool failed to generate a graph image",
    .duplicate_parameter = L"Duplicate parameter '%a' found",
    .cannot_write_analysis_file = L"Could not write the analysis report to '%a'",
    .cannot_read_source_file = L"Could not read the source code file at '%a'",
    .compilation_warning = L"Warning in '%a', %zu.%zu: %s",
    .compilation_error = L"Error in '%a', %zu.%zu: %s",
    .critical_compilation_error = L"Fatal error in '%a', %zu.%zu: %s",
    .unknown_symbol = L"Unknown symbol '%c'",
    .integer_literal_out_of_range = L"Integer literal is outside the signed 64-bit range",
    .unclosed_quotation_mark = L"Unmatched quote found in string literal; expected closing quote",
    .invalid_escape_sequence = L"Invalid escape sequence '\\%c' in string literal",
    .unclosed_opening_bracket =
        L"Unclosed opening bracket: expected a closing bracket to match '%c'",
    .missing_opening_bracket = L"Missing opening bracket corresponding to '%c'",
    .brackets_do_not_match = L"Closing bracket '%c' does not match the opening bracket '%c'",
    .not_a_statement = L"Token '%s' is not a statement allowed here",
    .expected_expression = L"Unexpected token '%s', expression expected at this position",
    .expected_lvalue = L"Left-hand side expression expected, got '%s' instead",
    .expected_comma_between_args = L"Expected comma between function arguments",
    .expected_expr_after_comma = L"Expected expression after comma in argument list",
    .expected_var_declaration = L"Variable declaration expected after 'var' keyword",
    .expected_const_declaration = L"Constant declaration expected after 'const' keyword",
    .expected_var_after_comma = L"Expected another variable declaration after comma",
    .expected_const_after_comma = L"Expected another constant declaration after comma",
    .invalid_var_declaration_syntax =
        L"Expected either variable name or name with value assignment, but got '%s'",
    .invalid_const_declaration_syntax = L"Expected name with value assignment, but got '%s'",
    .invalid_function_argument = L"Function argument must be an identifier, but got '%s'",
    .invalid_parenthesized_expression = L"Inside parentheses there must be exactly one expression",
    .variable_used_before_declaration = L"Variable '%s' is used before its declaration",
    .invalid_for_header = L"Expected for (initial; condition; step)",
    .expected_statement_after_for = L"Expected statement after for header",
    .expected_condition_after_if = L"Expected parenthesized condition after 'if' keyword",
    .expected_statement_after_if = L"Statement expected after 'if' keyword",
    .expected_statement_after_else = L"Statement expected after 'else' keyword",
    .else_without_if = L"'else' keyword without matching 'if'",
    .duplicate_else_branch = L"Unexpected 'else' after an existing 'else' branch",
    .expected_try_statement = L"Expected a statement after 'try'",
    .expected_catch = L"Expected 'catch' after the try statement",
    .invalid_catch_binding = L"Expected a single identifier in parentheses after 'catch'",
    .expected_catch_block = L"Expected a braced statement list after catch parameter",
    .catch_without_try = L"Catch without matching try",
    .expected_throw_value = L"Expected an expression after 'throw'",
    .uncaught_exception = L"Uncaught exception: %s",
};

/** @brief The message structure for Russian language. */
static messages_t russian = {
    .help = L"Использование: goat [параметры] <входной_файл> [аргументы скрипта...]\n"
            L"\n"
            L"Параметры:\n"
            L"  --compile                    Сохранить <имя>.gbin без выполнения\n"
            L"  --run                        Выполнить .gbin без компиляции (native: auto)\n"
            L"  --optimize <none|all>         Уровень оптимизаций (по умолчанию: all)\n"
            L"  --native <off|auto|required>  Нативное исполнение (по умолчанию: off)\n"
            L"  --print-native               Напечатать счётчики нативных вызовов\n"
            L"  --save-native <file>         Сохранить счётчики нативных вызовов\n"
            L"  --print-analysis              Вывести события анализа\n"
            L"  --save-analysis <file>      Сохранить события анализа в UTF-8\n"
            L"  --print-c                    Вывести C-модуль без исполнения программы\n"
            L"  --save-c                     Сохранить C-модуль рядом с исходником в <имя>.c\n"
            L"  --save-library               Собрать <имя>.so/.dll без исполнения (CC)\n"
            L"  --print-bytecode              Вывести сгенерированный байткод\n"
            L"  --print-source-code           Вывести восстановленный исходный код Goat\n"
            L"  --save-graph <file.png|svg>  Сгенерировать изображение AST-графа\n"
            L"  -l, --lang, --language <lang> Выбрать язык сообщений\n"
            L"  -w, --enable-warnings         Включить предупреждения компилятора\n"
            L"  -h, --help, /?                Показать эту справку\n",
    .native_compile_failed = L"Ошибка нативной компиляции (%s): компилятор '%a', файл '%a', "
                             L"код %ld, сигнал %d, системная ошибка %a, ошибка очистки %a, ошибка "
                             L"Win32 %u, очистка Win32 %u",
    .native_diagnostics_truncated = L"Вывод компилятора обрезан до 65536 байт",
    .native_input_conflict = L"Библиотека не должна перезаписывать исходный файл",
    .bad_native_mode = L"Неизвестный нативный режим: '%a' (ожидается off, auto или required)",
    .bad_native_options = L"Нативное исполнение требует --optimize all; экспорт C/библиотеки "
                          L"несовместим с нативным исполнением и отчётами",
    .native_report_conflict = L"Нативный отчёт не должен перезаписывать исходный файл",
    .cannot_write_native_report = L"Не удалось записать нативный отчёт в '%a'",
    .native_prepare_failed = L"Ошибка нативной подготовки (%a): %a",
    .bad_c_options = L"Экспорт C требует --optimize all и несовместим с другими опциями --print",
    .cannot_write_c_file = L"Не удалось записать C-код в '%a' (перезапись исходника запрещена)",
    .c_omitted = L"Генерация C пропустила %s: %s",
    .memory_leak = L"Обнаружена утечка памяти в %zu байт",
    .no_input_file = L"Не указан входной файл",
    .unknown_option = L"Неизвестный параметр командной строки: '%a'",
    .missing_specification = L"Отсутствует значение для параметра '%a'",
    .bad_optimization_level = L"Неизвестный уровень оптимизаций: '%a' (ожидается none или all)",
    .bad_graph_file =
        L"Файл, в который сохраняется изображение графа, должен быть типа PNG или SVG",
    .no_graphviz =
        L"Утилита GraphViz, необходимая для генерации изображения графа, не установлена в системе",
    .graphviz_failed = L"Утилита GraphViz не смогла сгенерировать изображение графа",
    .duplicate_parameter = L"Параметр '%a' повторяется",
    .cannot_write_analysis_file = L"Не удалось записать отчёт анализа в '%a'",
    .cannot_read_source_file = L"Не удалось прочесть исходный файл '%a'",
    .compilation_warning = L"Предупреждение в файле '%a', %zu.%zu: %s",
    .compilation_error = L"Ошибка в файле '%a', %zu.%zu: %s",
    .critical_compilation_error = L"Критическая ошибка в файле '%a', %zu.%zu: %s",
    .unknown_symbol = L"Неизвестный символ '%c'",
    .integer_literal_out_of_range = L"Целочисленный литерал вне знакового 64-битного диапазона",
    .unclosed_quotation_mark = L"В строковом литерале пропущена закрывающая кавычка",
    .invalid_escape_sequence =
        L"Неправильная управляющая последовательность '\\%c' в строковом литерале",
    .unclosed_opening_bracket = L"Нет закрывающей скобки, соответствующей '%c'",
    .missing_opening_bracket = L"Нет открывающей скобки, соответствующей '%c'",
    .brackets_do_not_match = L"Закрывающая скобка '%c' не соответствует открывающей '%c'",
    .not_a_statement = L"Токен '%s' здесь недопустим, ожидается инструкция языка",
    .expected_expression = L"Токен '%s' здесь недопустим, в этом месте ожидается выражение",
    .expected_lvalue = L"Ожидается левостороннее выражение, но получено '%s'",
    .expected_comma_between_args = L"Ожидается запятая между аргументами функции",
    .expected_expr_after_comma = L"Ожидается выражение после запятой в списке аргументов",
    .expected_var_declaration = L"После ключевого слова 'var' ожидается определение переменной",
    .expected_const_declaration = L"После ключевого слова 'const' ожидается определение константы",
    .expected_var_after_comma = L"После запятой ожидается определение следующей переменной",
    .expected_const_after_comma = L"После запятой ожидается определение следующей константы",
    .invalid_var_declaration_syntax =
        L"Ожидается либо имя переменной, либо имя с присваиванием значения, но получено '%s'",
    .invalid_const_declaration_syntax = L"Ожидается имя с присваиванием значения, но получено '%s'",
    .invalid_function_argument = L"Аргумент функции должен быть идентификатором, но получено '%s'",
    .invalid_parenthesized_expression =
        L"Внутри круглых скобок должно быть выражение, причем ровно одно",
    .variable_used_before_declaration = L"Переменная '%s' используется до ее объявления",
    .invalid_for_header = L"Ожидается for (инициализация; условие; шаг)",
    .expected_statement_after_for = L"Ожидается оператор после заголовка for",
    .expected_condition_after_if =
        L"После ключевого слова 'if' ожидается условие в круглых скобках",
    .expected_statement_after_if = L"После ключевого слова 'if' ожидается инструкция языка",
    .expected_statement_after_else = L"После ключевого слова 'else' ожидается инструкция языка",
    .else_without_if = L"Ключевое слово 'else' без соответствующего 'if'",
    .duplicate_else_branch = L"После ветки 'else' не может следовать еще одна ветка 'else'",
    .expected_try_statement = L"После 'try' ожидается оператор",
    .expected_catch = L"После оператора try ожидается 'catch'",
    .invalid_catch_binding = L"После 'catch' ожидается один идентификатор в круглых скобках",
    .expected_catch_block = L"После параметра catch ожидается блок в фигурных скобках",
    .catch_without_try = L"Catch без соответствующего try",
    .expected_throw_value = L"После 'throw' ожидается выражение",
    .uncaught_exception = L"Неперехваченное исключение: %s",
};

/** @brief Pointer to the current message structure. */
static messages_t *messages = &english;

const messages_t *get_messages() {
    return messages;
}

#define MAX_LANG_NAME_LEN 16

void set_language(const char *lang) {
    char buff[MAX_LANG_NAME_LEN];
    int i;
    for (i = 0; i < MAX_LANG_NAME_LEN - 1 && lang[i] != '\0'; i++) {
        buff[i] = tolower(lang[i]);
    }
    buff[i] = '\0';

    if (strcmp("ru", buff) == 0) {
        messages = &russian;
    } else {
        messages = &english;
    }
}

void init_messages() {
    const char *lang = getenv("GOAT_LANGUAGE");
    if (lang != NULL) {
        set_language(lang);
    }
}
