/**
 * @file options.h
 * @copyright 2026 Ivan Kniazkov
 * @brief Definitions and function prototypes for command-line options parsing.
 */

#pragma once

#include "lib/path.h"
#include "lib/vector.h"

#include <stdbool.h>

typedef struct options_t options_t;

/** @brief Optional analysis and code optimization level. */
typedef enum { OPTIMIZATION_NONE, OPTIMIZATION_ALL } optimization_level_t;

/** @brief Storing parsed command-line options. */
struct options_t {
    /** @brief Path to the input file. */
    path_t *input_file;

    /** @brief Defaults to OPTIMIZATION_ALL. */
    optimization_level_t optimization_level;

    /** @brief Language for the command-line interface (CLI) error messages. */
    const char *language;

    /**
     * @brief Flag to enable printing of the generated Goat source code.
     *
     * If set to `true`, the program will output the re-generated Goat source code after parsing
     * input files to the Goat syntax tree and optimizing it.
     */
    bool print_source_code;

    /**
     * @brief Flag to enable printing of the generated bytecode.
     *
     * If set to `true`, the program will output the generated bytecode representation after
     * processing the input file.
     */
    bool print_bytecode;

    /** @brief Print chronological analysis observations to stdout. */
    bool print_analysis;

    /** @brief Optional UTF-8 analysis report destination. */
    path_t *analysis_output_file;

    /** @brief Flag to enable compiler warnings. */
    bool enable_warnings;

    /**
     * @brief Path to the output file for graph visualization (DOT/GraphViz).
     *
     * If non-NULL, specifies the file where the program should save the generated graph
     * representation. If NULL, graph visualization is disabled.
     */
    path_t *graph_output_file;

    /** @brief Arguments to be passed to the script. */
    vector_t *script_args;
};

/**
 * @brief Creates and initializes an options_t structure.
 *
 * The structure must be freed using `destroy_options()`.
 */
options_t *create_options();

/**
 * @brief Parses command-line arguments into an options_t structure.
 *
 * If parsing fails (due to missing values, unknown options, or other errors), the function returns
 * `NULL`.
 * @return A pointer to an `options_t` structure if parsing is successful, otherwise `NULL`.
 */
options_t *parse_options(int argc, char **argv);

/** @brief Destroys an options_t structure and frees all associated memory. */
void destroy_options(options_t *opt);
