/*
    Copyright 2023 Ivan Kniazkov

    Use of this source code is governed by an MIT-style license
    that can be found in the LICENSE.txt file or at https://opensource.org/licenses/MIT.
*/

#pragma once

namespace goat {

    /**
     * @brief All possible token types
     */
    enum class token_type {
        unknown = 0,
        identifier,
        opening_bracket,
        closing_bracket
    };

    /**
     * @brief A token, that is, a structure that is generated by the scanner
     *   and defines some piece of source code
     */
    struct token {
        /**
         * @brief Virtual destructor for inheritors
         */
        virtual ~token() {
        }

        /**
         * @brief The type of the token
         */
        token_type type;

        /**
         * @brief Source code file name
         */
        const char * file_name;

        /**
         * @brief Line number (starts from 1)
         */
        unsigned int line;

        /**
         * @brief Column number (starts from 1)
         */
        unsigned int column;

        /**
         * @brief Pointer to token source code
         */
        const char * code;

        /**
         * @brief Token length (in characters), always non-zero
         */
        unsigned int length;
    };
};
