name: build_goat
run-name: ${{ github.actor }} is building the Goat interpreter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: ./build.sh
        shell: bash
